package com.mycompany.trabalhomvcswing.view;

<<<<<<< HEAD
import com.mycompany.trabalhomvcswing.model.JurosComposto;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class SimularJurosView extends javax.swing.JFrame {

    private static int idJuros;

=======
import com.mycompany.trabalhomvcswing.controller.SimularJuros;
import javax.swing.JOptionPane;

public class SimularJurosView extends javax.swing.JFrame {

>>>>>>> 1744141065066c63aba2b0bc5cbc23e1e45e27ff
    public SimularJurosView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
<<<<<<< HEAD
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
=======
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
>>>>>>> 1744141065066c63aba2b0bc5cbc23e1e45e27ff
    private void initComponents() {

        lblSimularJuros = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMontante = new javax.swing.JTextField();
        txtTaxaJurosAnos = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPeriodoAnos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
<<<<<<< HEAD
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabelaJuros = new javax.swing.JTable();
        btnDeletar = new javax.swing.JButton();
=======
>>>>>>> 1744141065066c63aba2b0bc5cbc23e1e45e27ff

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simular Juros Composto");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(0, 255, 255));

        lblSimularJuros.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblSimularJuros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSimularJuros.setText("Simular Juros");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 21, 91));
        jLabel6.setText("Montante");

        txtMontante.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtMontante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontanteActionPerformed(evt);
            }
        });

        txtTaxaJurosAnos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 21, 91));
        jLabel2.setText("Taxa do juros(anos)");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 21, 91));
<<<<<<< HEAD
        jLabel3.setText("Periodo em anos");
=======
        jLabel3.setText("Taxa do juros(anos)");
>>>>>>> 1744141065066c63aba2b0bc5cbc23e1e45e27ff

        btnCalcular.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnCalcular.setForeground(new java.awt.Color(153, 21, 91));
        btnCalcular.setText("Calcular");
        btnCalcular.setBorderPainted(false);
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        btnSair.setBackground(new java.awt.Color(204, 204, 204));
        btnSair.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnSair.setForeground(new java.awt.Color(255, 102, 102));
<<<<<<< HEAD
        btnSair.setText("Voltar");
=======
        btnSair.setText("Sair");
>>>>>>> 1744141065066c63aba2b0bc5cbc23e1e45e27ff
        btnSair.setBorderPainted(false);
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

<<<<<<< HEAD
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Exemplo: (Montante = 1000  Taxa do juros(anos)=5  Periodo em anos=3)");

        jTabelaJuros.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {
                        "Id", "Montante", "taxa de juros anual", "Periodo em anos", "Resultado"
                }) {
            boolean[] canEdit = new boolean[] {
                    false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTabelaJuros);
        if (jTabelaJuros.getColumnModel().getColumnCount() > 0) {
            jTabelaJuros.getColumnModel().getColumn(0).setPreferredWidth(2);
        }

        btnDeletar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnDeletar.setForeground(new java.awt.Color(153, 21, 91));
        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblSimularJuros, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnCalcular, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.PREFERRED_SIZE, 254,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnSair, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.PREFERRED_SIZE, 254,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(240, 240, 240))
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel6)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(txtMontante,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 79,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel2)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(txtTaxaJurosAnos,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 79,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel3)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(txtPeriodoAnos,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 68,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(btnDeletar,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 179,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblSimularJuros)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(txtMontante, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2)
                                        .addComponent(txtTaxaJurosAnos, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtPeriodoAnos, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addGap(16, 16, 16)
                                .addComponent(btnCalcular)
                                .addGap(18, 18, 18)
                                .addComponent(btnSair)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDeletar)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
=======
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSimularJuros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMontante, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTaxaJurosAnos, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtPeriodoAnos, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(240, 240, 240))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(240, 240, 240))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSimularJuros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtMontante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtTaxaJurosAnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPeriodoAnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(50, 50, 50)
                .addComponent(btnCalcular)
                .addGap(18, 18, 18)
                .addComponent(btnSair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
>>>>>>> 1744141065066c63aba2b0bc5cbc23e1e45e27ff

        pack();
    }// </editor-fold>//GEN-END:initComponents

<<<<<<< HEAD
    private void txtMontanteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtMontanteActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtMontanteActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCalcularActionPerformed
        // Extrai o valor do campo de texto txtMontante e o converte para um valor
        // double
        double montante = Double.parseDouble(txtMontante.getText());

        // Extrai o valor do campo de texto txtTaxaJurosAnos e o converte para um valor
        // double
        double taxaJurosAnos = Double.parseDouble(txtTaxaJurosAnos.getText());

        // Extrai o valor do campo de texto txtPeriodoAnos e o converte para um valor
        // inteiro
        int periodoAnos = Integer.parseInt(txtPeriodoAnos.getText());

        // Cria uma instância da classe JurosComposto com os valores obtidos dos campos
        // de texto
        JurosComposto juros = new JurosComposto(montante, taxaJurosAnos, periodoAnos);

        // Calcula os juros compostos usando a instância juros
        double resultado = juros.calcularJurosCompostos();

        // Cria um objeto DecimalFormat para formatar o resultado com duas casas
        // decimais
        DecimalFormat df = new DecimalFormat("#.##");

        // Obtém o modelo da tabela jTabelaJuros
        DefaultTableModel tabela = (DefaultTableModel) jTabelaJuros.getModel();

        // Adiciona uma nova linha à tabela com os valores calculados
        tabela.addRow(new Object[] { idJuros, montante, taxaJurosAnos, periodoAnos, df.format(resultado) });

        // Incrementa o idJuros para a próxima entrada
        idJuros++;

    }// GEN-LAST:event_btnCalcularActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSairActionPerformed
=======
    private void txtMontanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontanteActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed

        Double capital = Double.parseDouble(txtMontante.getText()); // retorna um valor primitivo double
        // Double montante = Double.valueOf(txtMontante.getText()); // retorna um Objeto Double
        Double taxaJurosAnos = Double.valueOf(txtTaxaJurosAnos.getText());
        Integer periodoAnos = Integer.valueOf(txtPeriodoAnos.getText());

        SimularJuros juros = new SimularJuros();
        double resultado = juros.calcularJurosCompostos(capital, taxaJurosAnos, periodoAnos);
        
        JOptionPane.showMessageDialog(null, "Valor total dos juros: " + String.format("%.2f", resultado), "Juros Compostos", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
>>>>>>> 1744141065066c63aba2b0bc5cbc23e1e45e27ff
        HomeView frame = new HomeView();
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
        dispose();

<<<<<<< HEAD
    }// GEN-LAST:event_btnSairActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDeletarActionPerformed

        // Solicita ao usuário que informe o ID que deseja deletar
        String id = JOptionPane.showInputDialog("Informe o ID que deseja deletar do seu Histórico");

        // Converte o ID fornecido em um valor inteiro
        Integer identificador = Integer.valueOf(id);

        // Obtém o modelo da tabela jTabelaJuros
        DefaultTableModel tabela = (DefaultTableModel) jTabelaJuros.getModel();

        // Loop através de todas as linhas da tabela
        for (int linha = 0; linha < tabela.getRowCount(); linha++) {
            // Obtém o valor da primeira coluna (coluna 0) da linha atual e converte para um
            // valor inteiro
            int aux = Integer.valueOf(tabela.getValueAt(linha, 0).toString());

            // Verifica se o ID fornecido é igual ao ID da linha atual
            if (identificador == aux) {
                // Remove a linha da tabela onde o ID corresponde
                tabela.removeRow(linha);
                System.out.println("Deletado: " + linha); // Exibe uma mensagem informando que a linha foi deletada
            }
        }

    }// GEN-LAST:event_btnDeletarActionPerformed
=======
    }//GEN-LAST:event_btnSairActionPerformed
>>>>>>> 1744141065066c63aba2b0bc5cbc23e1e45e27ff

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
<<<<<<< HEAD
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
=======
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
>>>>>>> 1744141065066c63aba2b0bc5cbc23e1e45e27ff
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
<<<<<<< HEAD
            java.util.logging.Logger.getLogger(SimularJurosView.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimularJurosView.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimularJurosView.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimularJurosView.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>
=======
            java.util.logging.Logger.getLogger(SimularJuros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimularJuros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimularJuros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimularJuros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
>>>>>>> 1744141065066c63aba2b0bc5cbc23e1e45e27ff

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimularJurosView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
<<<<<<< HEAD
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabelaJuros;
=======
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
>>>>>>> 1744141065066c63aba2b0bc5cbc23e1e45e27ff
    private javax.swing.JLabel lblSimularJuros;
    private javax.swing.JTextField txtMontante;
    private javax.swing.JTextField txtPeriodoAnos;
    private javax.swing.JTextField txtTaxaJurosAnos;
    // End of variables declaration//GEN-END:variables
}
